import { z } from 'zod';

export const planFormSchema = z.object({
  name: z.string().min(2, 'O nome deve ter pelo menos 2 caracteres'),
  slug: z.string().optional(),
  short_description: z.string().optional().default(''),
  description: z.string().optional().default(''),
  monthly_price: z.coerce.number().min(0, 'O preço mensal não pode ser negativo'),
  yearly_price: z.coerce.number().min(0, 'O preço anual não pode ser negativo'),
  yearly_discount_percent: z.coerce.number().min(0).max(100).optional().nullable(),
  is_featured: z.boolean().default(false),
  has_trial: z.boolean().default(false),
  trial_days: z.coerce.number().int().min(0).optional().nullable(),
  display_order: z.coerce.number().int().min(0).optional().nullable(),
  badge: z.string().optional().default(''),
  color: z.string().optional().default(''),
  max_users: z.coerce.number().int().min(0).optional().nullable(),
  max_clients: z.coerce.number().int().min(0).optional().nullable(),
  max_pets: z.coerce.number().int().min(0).optional().nullable(),
  max_appointments: z.coerce.number().int().min(0).optional().nullable(),
  max_products: z.coerce.number().int().min(0).optional().nullable(),
  max_services: z.coerce.number().int().min(0).optional().nullable(),
  max_stock_items: z.coerce.number().int().min(0).optional().nullable(),
  max_documents: z.coerce.number().int().min(0).optional().nullable(),
  max_attachments: z.coerce.number().int().min(0).optional().nullable(),
  max_storage_mb: z.coerce.number().int().min(0).optional().nullable(),
  features: z.object({
    pdv: z.boolean().default(false),
    reports: z.boolean().default(false),
    boarding: z.boolean().default(false),
    grooming: z.boolean().default(false),
    whatsapp: z.boolean().default(false),
    financial: z.boolean().default(false),
    inventory: z.boolean().default(false),
    surgeries: z.boolean().default(false),
    multi_user: z.boolean().default(false),
    vaccination: z.boolean().default(false),
    appointments: z.boolean().default(false),
    external_api: z.boolean().default(false),
    integrations: z.boolean().default(false),
    hospitalization: z.boolean().default(false),
    advanced_dashboard: z.boolean().default(false),
  }),
  is_active: z.boolean().default(true),
});
